version: '3'
services:
  flask-app:
    image: python:3.8-slim
    container_name: sw2
    ports:
      - "6001:5000"
    volumes:
      - ./:/app
    networks:
      - sw2-network
    working_dir: /app
    tty: true
    command: tail -f /dev/null

networks:
  sw2-network:
    external: true