version: '3'
services:
  flask-app:
    image: python:3.8-slim
    container_name: sw2
    ports:
      - "8000:5000"
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    command: tail -f /dev/null
